version: '3.4'

services:
  template.backend.api:
    image: ${DOCKER_REGISTRY-}templatebackendapi
    build:
      context: .
      dockerfile: Template.Backend.Api/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=TemplateBackendDb;User=sa;Password=sqlP@ssw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;integrated security=false"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=yourStrongP@ssw0rd"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    restart: on-failure

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - "SA_PASSWORD=sqlP@ssw0rd"
      - "ACCEPT_EULA=Y"
    ports:
      - '1433:1433'
  
